export const ROUTES = {
  SPLASH: "/splash",
  LOGIN: "/login",
  HOME: "/",
  GUIDE: "/guide",
  GUIDE_DETAIL: "/guide/:stepId",
  SUPPORT: "/support",
  SUPPORT_DETAIL: "/support/:supportId",
  USED: "/used",
  USED_SEARCH: "/used/search",
  USED_SEARCH_RESULT: "/used/search/result",
  USED_BUSINESS_AUTH: "/used/business-auth",
  USED_WRITE: "/used/write",
  USED_DETAIL: "/used/:productId",
  USED_CHAT: "/used/chat/:productId",
} as const;
